services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./backend/conversations:/app/conversations
      - ./backend/profiles:/app/profiles
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  node_modules:

